name: CI
on: push
jobs:
  trufflehog:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Secret Scanning using TruffleHog
      uses: trufflesecurity/trufflehog@main
      with:
        base: ""
        head: ${{ github.ref_name }}
        extra_args: --debug --only-verified --github-actions 
