name: CI
on: push
jobs:
  trufflehog:
    runs-on: ubuntu-latest

    env:
      ORG_NAME: ${{ secrets.TRUFFLEHOG_ORG_NAME }}
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Secret Scanning
      run: |
        echo "Branch name is ${GITHUB_REF##*/}"
        docker run --rm -e DOCKER_TTY=0 -v "$PWD:/pwd" trufflesecurity/trufflehog:latest git file://. --since-commit main --only-verified --fail --debug > trufflehog_result.txt  
        # Add error handling if the previous command fails
        if [ $? -ne 0 ]; then
          echo "Trufflehog execution failed"
          exit 1
        fi

    - name: Upload Trufflehog Result
      uses: actions/upload-artifact@v2
      with:
        name: trufflehog-result
        path: trufflehog_result.txt
