name: CI
on: push
jobs:
  trufflehog:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Secret Scanning using TruffleHog
      uses: trufflesecurity/trufflehog@main
      with:
        base: ""
        head: ${{ github.ref_name }}
        extra_args: --debug --only-verified --json=trufflehog-secret-scan-result.json
    - name: Upload Trufflehog Result
      uses: actions/upload-artifact@v2
      with:
        name: TruffleHog secret scan result
        path: trufflehog-secret-scan-result.json
